version: "3"

services:
  db:
    image: postgres:11
    restart: always
    network_mode: "host"
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=odoo
    volumes:
      - "../db_data_odoo12/:/var/lib/postgresql/data"
      - "../db_backup_odoo12/:/db_backup/"
  web:
    build: .
    restart: always
    volumes:
      - ".:/src"
      - "./storage:/root/.local/share/Odoo"
    network_mode: "host"
    depends_on:
      - db
