version: "3"

services:
  db:
    image: postgres:11
    network_mode: "host"
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=odoo
    volumes:
      - "./db_data_odoo12/:/var/lib/postgresql/data"
      - "./db_backup_odoo12/:/db_backup/"
  web:
    build: .
    volumes:
      - ".:/src"
      - "./storage:/root/.local/share/Odoo"
    network_mode: "host"
    environment:
      - ODOO_ENV=dev
    depends_on:
      - db
#  pgadmin:
#    image: dpage/pgadmin4:latest
#    network_mode: "host"
#    environment:
#      - PGADMIN_LISTEN_PORT=8000
#      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#      - PGADMIN_DEFAULT_PASSWORD=admin
#    depends_on:
#      - db
