from . import Anexo
from . import Aquisicao
from . import AreaTrabalho
from . import Autor
from . import CategoriaCnpq
from . import OrientadorTitulacao
from . import Orientador
from . import PalavraChave
from . import Publicacao
from . import Responsavel
from . import TipoPublicacao
from . import Curso_override
from . import Pessoa_override
