from . import AutorizacaoChave
from . import Chave
from . import Gerente
from . import Pessoa_override
from . import RegistroChave
from . import Responsavel
from . import Seguranca
from . import SolicitacaoChave
from . import Transferencia
